"""switch include to text

Revision ID: 44b5d2280d42
Revises: 24abc136c25a
Create Date: 2023-06-23 05:42:43.615937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44b5d2280d42'
down_revision = '24abc136c25a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
