"""default time for user

Revision ID: 5be96ace3b5c
Revises: 24abc136c25a
Create Date: 2023-06-24 09:20:58.092473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5be96ace3b5c'
down_revision = '24abc136c25a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_login',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_login',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
