"""add batch for major

Revision ID: 6033fe2623a4
Revises: 44f1b28accd2
Create Date: 2024-07-21 16:11:27.067417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6033fe2623a4'
down_revision = '44f1b28accd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('major', sa.Column('batch', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_major_batch'), 'major', ['batch'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_major_batch'), table_name='major')
    op.drop_column('major', 'batch')
    # ### end Alembic commands ###
